import type { Metadata } from "next";
import { Familjen_Grotesk, Faster_One } from "next/font/google";
import "./globals.css";

const familjen_grotesk = Familjen_Grotesk({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: '--font-familjen-rotesk'
});

const faster_one = Faster_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-faster-one',
});

export const metadata: Metadata = {
  title: "HAPPY GAME DAY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${familjen_grotesk.variable} ${faster_one.variable}`}>{children}</body>
    </html>
  );
}
