import type { Metadata } from "next";
import { Inter, Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const inter = Inter({
   subsets: ["latin"],
   variable: '--font-inter'
});

const montserrat_alternates = Montserrat_Alternates({
  subsets: ['latin'],
  weight: ['200', '400', '500', '600', '800'],
  variable: '--font-montserrat-alternates',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat_alternates.variable}`}>{children}</body>
    </html>
  );
}
